=== anjumfatima90/osgi-1/org.osgi.test.cases.zigbee/zigbee-tck.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://org.osgi/zigbee-tck"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:simpleType name="EndpointID">
    <xs:union memberTypes="xs:unsignedByte">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{2}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="ProfileID" id="ProfileID">
    <xs:union memberTypes="xs:unsignedShort">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{4}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="ManufacturerCode" id="ManufacturerCode">
    <xs:union memberTypes="xs:unsignedInt">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{4}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="UnsignedInt16HexDec">
    <xs:union memberTypes="xs:unsignedShort">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{4}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="DeviceID" id="DeviceID">
    <xs:union memberTypes="xs:unsignedShort">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:pattern value="0x[0-9a-fA-F]{4}" />
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>

  <xs:simpleType name="IEEEAddress" id="IEEEAddress">
    <xs:restriction base="xs:token">
      <xs:pattern value="[0-9a-fA-F]{8}" />
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="nodeDescriptor">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:short" name="type" use="required" />
          <xs:attribute type="xs:short" name="frequencyBand" use="required" />
          <xs:attribute type="ManufacturerCode" name="manufacturerCode" use="required" />
          <xs:attribute type="xs:int" name="maxBufferSize" use="required" />
          <xs:attribute type="xs:boolean" name="isUserDescriptorAvailable" use="required" />
          <xs:attribute type="xs:boolean" name="isComplexDescriptorAvailable" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="powerDescriptor">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="xs:unsignedByte" name="currentPowerMode" use="required" />
          <xs:attribute type="xs:unsignedByte" name="currentPowerSource" use="required" />
          <xs:attribute type="xs:unsignedByte" name="currentPowerSourceLevel" use="required" />
          <xs:attribute type="xs:boolean" name="isConstantMainsPowerAvailable" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="simpleDescriptor">
    <xs:annotation>
      <xs:documentation>
        This element represents a ZigBee Endpoint Simple Descriptor. It does not define all the attributes actually
        specified by the ZigBee Specification, but only those that will be actually checked by the
        TCK.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute type="DeviceID" name="deviceId" use="required" />
          <xs:attribute type="xs:int" name="version" use="required" />
          <xs:attribute type="ProfileID" name="profileId" use="required" />
          <xs:attribute type="xs:string" name="inputClusters" use="required" />
          <xs:attribute type="xs:string" name="outputClusters" use="required" />
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="cluster">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zb:command" xmlns:zb="http://org.osgi/zigbee-tck" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="endpoint">
    <xs:annotation>
      <xs:documentation>
        This element represent a ZigBee Active Endpoint on the ZigBee node. Define the simpleDescriptor and the
        client and server clusters.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zb:simpleDescriptor" xmlns:zb="http://org.osgi/zigbee-tck" />
        <xs:element ref="zb:clusters" xmlns:zb="http://org.osgi/zigbee-tck" />
      </xs:sequence>
      <xs:attribute type="EndpointID" name="id" />
      <xs:attribute type="xs:unsignedInt" name="inputClustersNumber" use="required" />
      <xs:attribute type="xs:unsignedInt" name="outputClustersNumber" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="endpoints">
    <xs:annotation>
      <xs:documentation>
        This tag must contain a list of active endpoints available on the ZigBee Node.
        The total number of this
        active endpoints must be assigned to the 'activeEndpointsNumber' attribute.
        On the other hand the list itself must not be
        exhaustive, because the TCK will only try to check only the first one.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zb:endpoint" xmlns:zb="http://org.osgi/zigbee-tck" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="node">
    <xs:annotation>
      <xs:documentation>
        A node represents a ZigBee device. Fill the ieeeAddress, userDescription attributes here, according to the
        device characteristics. No need to explicitly describe in this xml file all the active endpoints available on the ZigBee
        node, but remember to set the activeEndpointsNumber attribute of the 'endpoints' element to the total number
        of active
        endpoints that are available inside this
        ZigBee device.
        This value will be compared with the total number of ZigBeeEndpoint
        services registered by this
        ZigBeeNode in the
        OSGi framework.

        The ieeeAddress attribute is the IEEE address of the ZigBee node
        expressed as a decimal
        number. This
        attribute is mandatory.

        If the ZigBee node has a User Descriptor, the 'userDescription'
        attribute MUST contain
        the value
        stored in is the corresponding field of the User Descriptor. Otherwise this attribute may be
        omitted.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zb:nodeDescriptor" xmlns:zb="http://org.osgi/zigbee-tck">
          <xs:annotation>
            <xs:documentation>All the discovery tests will be done on this node. Please ensure that the simpleDescriptor tag is
              fully filled (the server and client clusters number must be filled accordingly). At least one attribute must be read
              only.
            </xs:documentation>
          </xs:annotation>
        </xs:element>
        <xs:element ref="zb:powerDescriptor" xmlns:zb="http://org.osgi/zigbee-tck" />
        <xs:element ref="zb:endpoints" xmlns:zb="http://org.osgi/zigbee-tck" />
      </xs:sequence>
      <xs:attribute type="IEEEAddress" name="ieeeAddress" use="required" />
      <xs:attribute type="IEEEAddress" name="hostIeeeAddress" use="required" />
      <xs:attribute type="xs:string" name="userDescription" use="required" />
      <xs:attribute type="xs:unsignedInt" name="activeEndpointsNumber" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="host">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zb:nodeDescriptor" xmlns:zb="http://org.osgi/zigbee-tck" />
      </xs:sequence>
      <xs:attribute type="UnsignedInt16HexDec" name="panId" use="required" />
      <xs:attribute type="xs:unsignedShort" name="channel" use="required" />
      <xs:attribute type="xs:unsignedByte" name="securityLevel" use="required" />
      <xs:attribute type="IEEEAddress" name="ieeeAddress" use="required" />
      <xs:attribute type="xs:long" name="discoveryTimeout" use="required" />
      <xs:attribute type="xs:long" name="invokeTimeout" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:element name="nodes">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zb:node" xmlns:zb="http://org.osgi/zigbee-tck" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="frame">
    <xs:annotation>
      <xs:documentation>
      </xs:documentation>
    </xs:annotation>
    <xs:attribute type="xs:unsignedInt" name="headerMinSize" use="required" />
    <xs:attribute type="xs:unsignedInt" name="headerMaxSize" use="required" />
  </xs:element>

  <xs:element name="configuration">
    <xs:annotation>
      <xs:documentation>
        This configuration file describes the ZigBee device that the tester is going
        to use to run the TCK against a
        RI. It must be filled properly, according to the ZigBee
        devices that will be actually used for the compliant tests. This
        template version is useful
        to understand how to fill all the required information.
        Keep in mind that the tests will fail
        if
        this file is not provided or properly filled. Timeouts are expressed in milliseconds.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="zb:frame" xmlns:zb="http://org.osgi/zigbee-tck" />
        <xs:element ref="zb:host" xmlns:zb="http://org.osgi/zigbee-tck" minOccurs="1" maxOccurs="1" />
        <xs:element ref="zb:nodes" xmlns:zb="http://org.osgi/zigbee-tck" minOccurs="1" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== anjumfatima90/osgi-1/org.osgi.test.cases.zigbee/zigbee-tck-template.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
    Copyright (c) Contributors to the Eclipse Foundation
   
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
   
        http://www.apache.org/licenses/LICENSE-2.0
   
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
   
    SPDX-License-Identifier: Apache-2.0 
 -->

<configuration xmlns="http://org.osgi/zigbee-tck" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://org.osgi/zigbee-tck zigbee-tck.xsd">
  <frame headerMaxSize="5" headerMinSize="3" />
  <host panId="0x0033" channel="16" securityLevel="0" ieeeAddress="30DE8600004000F4" discoveryTimeout="1000" invokeTimeout="3000">
    <nodeDescriptor type="2" frequencyBand="868" manufacturerCode="0x0045" maxBufferSize="36"
      isComplexDescriptorAvailable="false" isUserDescriptorAvailable="true" />
  </host>
  <nodes>
    <node ieeeAddress="30DE8600004000F3" hostIeeeAddress="30DE8600004000F4" userDescription="user description"
      activeEndpointsNumber="1">

      <nodeDescriptor type="1" frequencyBand="868" manufacturerCode="0x0045" maxBufferSize="36"
        isComplexDescriptorAvailable="false" isUserDescriptorAvailable="true" />

      <powerDescriptor currentPowerMode="2" currentPowerSource="1" currentPowerSourceLevel="1"
        isConstantMainsPowerAvailable="true" />

      <endpoints>
        <endpoint id="25" inputClustersNumber="2" outputClustersNumber="1">
          <simpleDescriptor deviceId="8" version="4" profileId="7" inputClusters="3,4" outputClusters="4">
          </simpleDescriptor>
        </endpoint>
      </endpoints>
    </node>
  </nodes>
</configuration>
